# Generated by Django 4.0.2 on 2022-02-10 07:52

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Bus',
            new_name='Flight',
        ),
    ]
